Metrics/LineLength:
  Max: 10000

Style/FileName:
  Enabled: False

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

Style/NumericLiteralPrefix:
    Enabled: false
